version: '3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: miorgash/livedoor
    container_name: livedoor
    volumes:
      - ..:/root/work
      - chive_v1.2mc5:/data/chive_v1.2mc5
      - chive_v1.2mc90:/data/chive_v1.2mc90
      - wikientvec_100d:/data/wikientvec_100d
      - wikientvec_300d:/data/wikientvec_300d
      - ldcc:/data/ldcc
    working_dir: /root/work
    ports:
      - "8888:8888"
    command: jupyter notebook --ip="0.0.0.0" --notebook-dir=/root/work --allow-root --no-browser
    restart: always
volumes:
  chive_v1.2mc5:
    external: 
      name: chive_v1.2mc5
  chive_v1.2mc90:
    external: 
      name: chive_v1.2mc90
  wikientvec_100d:
    external: 
      name: wikientvec_100d
  wikientvec_300d:
    external: 
      name: wikientvec_300d
  ldcc:
    external: 
      name: ldcc
